branches:
  only:
    - master

platform:
  - x64

clone_folder: C:\grr_src

cache:
  - '%LOCALAPPDATA%\pip\Cache -> **\install_for_build.bat'

install:
  - C:\grr_src\appveyor\install_for_build.bat
  - nuget install secure-file -ExcludeVersion
  # See https://www.appveyor.com/docs/how-to/secure-files/
  - >-
    secure-file\tools\secure-file
    -decrypt C:\grr_src\appveyor\appveyor_uploader_service_account.json.enc
    -secret %GCS_ENCRYPTION_KEY%

build_script:
  - >-
    C:\Python27-x64\python.exe
    C:\grr_src\appveyor\build_windows_templates.py
    --grr_src=C:\grr_src
    --output_dir=C:\grr_src\output
    --test_repack_install
  - powershell C:\grr_src\appveyor\deploy_to_gcs.ps1

artifacts:
  - path: output
    name: templates
    type: zip

# TODO(ogaro): Create a shared appveyor account, and use its encryption key.
environment:
  GCS_BUCKET: autobuilds.grr-response.com
  GCS_ENCRYPTION_KEY:
    secure: e4FbUfG/83Onfl5eDZ4O4uM5zyGVOBz2TBKf/gCs8fS093Hu2S5C5CTwGVDjE5+y
