branches:
  only:
    - master

environment:
  GCS_BUCKET: autobuilds.grr-response.com
  GCS_ENCRYPTION_KEY:
    secure: w3NY4lC2qczBJuds3B6yaMtXl8FlKk4SDuXP56YPmWI=

clone_folder: C:\grr_src

cache:
  - '%LOCALAPPDATA%\pip\Cache -> **\install_for_build.bat'

install:
  - C:\grr_src\appveyor\windows_templates\install_for_build.bat
  - nuget install secure-file -ExcludeVersion
  # See https://www.appveyor.com/docs/how-to/secure-files/
  - >-
    secure-file\tools\secure-file
    -decrypt C:\grr_src\appveyor\windows_templates\appveyor_uploader_service_account.json.enc
    -secret %GCS_ENCRYPTION_KEY%

build_script:
  - >-
    C:\Python36-x64\python.exe
    C:\grr_src\appveyor\windows_templates\build_windows_templates.py
    --grr_src=C:\grr_src
    --output_dir=C:\grr_src\output
    --test_repack_install
  - powershell C:\grr_src\appveyor\windows_templates\deploy_to_gcs.ps1
